### `scatter`

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
df = px.data.iris()
df.sample(6)

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
64,5.6,2.9,3.6,1.3,versicolor,2
20,5.4,3.4,1.7,0.2,setosa,1
108,6.7,2.5,5.8,1.8,virginica,3
41,4.5,2.3,1.3,0.3,setosa,1
142,5.8,2.7,5.1,1.9,virginica,3
71,6.1,2.8,4.0,1.3,versicolor,2

In [3]:
df['species_id'].unique()

array([1, 2, 3])

In [4]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species_id')
# it will plot species_id in continuous colors

fig.show()

In [5]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color=df['species_id'].astype(str))
# it will plot species_id in fixedcolors

fig.show()

In [6]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species', size='petal_length')

fig.show()

In [7]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species', size='petal_length', symbol='species')

fig.show()

---

In [8]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [9]:
# using 'facet'
fig = px.scatter(df, x='total_bill', y='tip', 
                color='smoker', facet_col='sex', title='Facet Col'
)
fig.show()

In [10]:
fig = px.scatter(df, x='total_bill', y='tip', 
                color='smoker', facet_row='time', title='Facet Row', height=600
)
fig.show()

In [11]:
fig = px.scatter(df, x='total_bill', y='tip', 
                color='smoker', facet_col='sex', facet_row='day', title='Facet Col and Facet Row', 
                height=600
)
fig.show()

In [12]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
# using Marginal Plot
    # REMEMBER BOTH marginal_x and marginal_y can take only 4 values : histogram, rug, box, violin

fig = px.scatter(df, x='tip', y='total_bill', color='smoker',
                marginal_x='histogram', marginal_y='rug',
                title='Scatter Plot with Histogram and Rug',
                height=700
)

fig.show()

In [14]:
# using Marginal Plot
fig = px.scatter(df, x='tip', y='total_bill', color='smoker',
                marginal_x='box', marginal_y='violin', trendline='ols',
                title='Scatter Plot with Boxplot and Violinplot',
                height=700
)

fig.show()

**REMEMBER** : `marginal_x` and `marginal_y` are only limited to scatterplot, density_headmap, density_contur.<br>
While using histogram, it can only take one marginal.

In [15]:

px.histogram(df, x="total_bill", marginal="box")